# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 01:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_secrets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='like',
            managers=[
                ('validation', django.db.models.manager.Manager()),
            ],
        ),
    ]
