def complimenting(dna_string):
    thing = ""
    for i in reversed(dna_string):
        if i == 'A':
            thing += 'T'
        if i == 'T':
            thing += 'A'
        if i == 'G':
            thing += 'C'
        if i == 'C':
            thing += 'G'
    print (thing)

complimenting('CCCATGTAGTAACCTGGGGCTCTGTAGCTTCGCAGAAACTGACGGCATACACAATGATGTTCGAGTTTCTAACGAAGCTAACGCTCACCGAAAAGGTATAAATCTGTTGTTTGCGAAGGCGGACAATATCCTGCTTTGTACGCAAATCCGCGTACTCAAACAATCCTAATGATGCACGCTATGGCATTAAGCACGAGCAACTGGTACGGCCATCACCGAAACCGTGGGTTATAGGCGAGGTTATGTGCAAGGGTACGCATGCACACAGAACATAGCGGCTCCCAATATTCGGAAACGATTTAAGATTCTAGGCAGTAATCTCCGGGAGACTCTTTTATCTAGCGGAGAGGCAACGGTCCTATTAATTGCGGCAAATATCTGCCCTGGGGGTGAAGGTCACTCAAAAAACTAAGTAAGACCTCGCCACAGTCATCATAAATTACATGCGGTATGCGCACACAGATGAGCGGTTGGAGCTGCGACCAGTGTAGGGCACCTACGGGTCGGGGGGCCGTCCGACCGGAAAGTCTATAAGGGGATCTGTTGCACACTAAAATTCTGAAGGTAGAGTTGCACACGGTCCTAATCCAAACGTGGGGGATAACCCGATGGGCGGAATATAATGGAGTCGACGGGTTACAACTTCAAATTGTCGCGCGGTTAATCGCAACTACCACATACAATGTGATTGAAGATTCGCACCCCTATGGAAACAGCTTTGTACCCGCCCTAGATTCTGCTGCGACTGATGCAGCAGCGTTGGTAATGAAGAGACGTACTCAACAAATCAATATGTAGGGCGCTTAGTACCGAAACCACGACGTTGAAGTAGAACGTCGCGCACGTTTGGCCCAGAGGCTTCCGTCATGCCATTAAAGGGGCTGCGCGGCAACACGCCGGTTGTGCGGGGTTTAAAGCCTCCACGAGAATGAAACCACACGCTCTATTTTACAGGGGCCTGGCTGCGAAAGACCGGAGACCAATC')
