def count(nucleotide):
    thingA = 0
    thingC = 0
    thingG = 0
    thingT = 0
    for i in nucleotide:
        if i == 'A':
            thingA += 1
        if i == 'C':
            thingC += 1
        if i == 'G':
            thingG += 1
        if i == 'T':
            thingT += 1
    print thingA, thingC, thingG, thingT


count('TTCCCGTCTCTCCAGCGAGAATCAGGACTTATCTGACGAGCCCTCCTACTCTACAACACAGCATCACGTACGCTACTTCAGTATGGCTACCCCTCACCTCGCGTGGGTGTGCTCAACGCACGGGAGGCTACCGGCTGCGCAGCCGTCTCGTAAGTTTTTTATGATGGAAGGATATTGGAGAGATAGTTTGTTCACACGCTAGTTGTATAATCTCAACTCGTGACGGGTCTTATCCCTCTCTGATAACAGCTTCGCGAACTCCGGGAGCTCTGTAGTTGTGCATTTGGTGGACCGTGCCGAATCATTGGGCCTCTGCTCCGCTCGCGTCGAGTAAAGCCATACGTTTCTCTTGCTTGATCCGTATTAAGACGTGATTGTCCCCCACACACTTCGGTATGTCACTTGCGTGACCGTGTTGCTGACTCCGAACCATGAATCACGCCGTCGCTAAGTGAACAGTAACAAATTGTTTTTGTAGGCCCGGCCTGAGGCTGCGTGGAACATACTATGAGCTAGGTTTTACAGGAGAGTCGTAGTAAGGCCGAAACAGTTAACTGACCCCAGTACACCTTCGGTCCGGCCCCTTTACCAGATCGCGGGACGAGCATTCGTACGGGCACACGGTCTTAAGTGGCTTGACGCACGAACTCACTACTACCGGATGCCAGCTATAGGTCTCTAGGGAAATCGATTGAGTTAAGGATCAGCGTCGCGGACGGCGGGGTCGGGGACGAAAGCGAAGTGACTCTCCGGAGAGACGGGATATAGCGGCCCTTTACGACATTCGTGAAACCCCCGTCCCAGGACAGTTTACACCGCCGCCTCAATAGCTACACTCTTCGATGGCTTA')
