# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='price',
            field=models.CharField(max_length=45),
        ),
    ]
